spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
  jpa:
    hibernate:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}