CREATE TABLE IF NOT EXISTS STORE.USERS (
    ID UUID PRIMARY KEY,
    NAME VARCHAR (200) NOT NULL,
    EMAIL VARCHAR (50) UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    ROLE TEXT CHECK (ROLE IN ('ADMIN', 'USER')) NOT NULL
)